name: Run Script on Master Push

on:
  push:
    branches:
      - master

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2  # 检出最后两个提交，以便可以比较 HEAD~1 和 HEAD

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Download ai-code-review jar to libs directory
        run: |
          mkdir -p ./libs
          wget -O ./libs/ai-code-review.jar https://github.com/JiangZhiyan00/ai-code-review-sdk/releases/download/1.0.0/ai-code-review-sdk-1.0.0.jar

      - name: Save Git Diff File, Add File Path To Env
        id: git-diff-content
        run: |
          mkdir -p /tmp/git_diff
          git diff HEAD~1 HEAD > /tmp/git_diff/diff.txt
          echo "GIT_DIFF_FILE_PATH=/tmp/git_diff/diff.txt" >> $GITHUB_ENV

      - name: Get repository name
        id: repo-name
        run: echo "REPO_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV

      - name: Get branch name
        id: branch-name
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Get commit author
        id: commit-author
        run: echo "COMMIT_AUTHOR=$(git log -1 --pretty=format:'%an <%ae>')" >> $GITHUB_ENV

      - name: Get commit message
        id: commit-message
        run: echo "COMMIT_MESSAGE=$(git log -1 --pretty=format:'%s')" >> $GITHUB_ENV

      - name: Print repository, branch name, commit author, and commit message
        run: |
          echo "Repository name is ${{ env.REPO_NAME }}"
          echo "Branch name is ${{ env.BRANCH_NAME }}"
          echo "Commit author is ${{ env.COMMIT_AUTHOR }}"
          echo "Commit message is ${{ env.COMMIT_MESSAGE }}"
          echo "Git Diff File Path is ${{ env.GIT_DIFF_FILE_PATH }}"
          echo "AI Model is ${{ secrets.MODEL }}"
          echo "Emails is ${{ secrets.EMAILS }}"

      - name: Run Code Review
        run: java -jar ./libs/ai-code-review.jar
        env:
          # Github 配置；GITHUB_REVIEW_LOG_URI「https://github.com/xfg-studio-project/openai-code-review-log」、GITHUB_TOKEN「https://github.com/settings/tokens」
          CODE_REVIEW_LOG_URL: ${{ secrets.CODE_REVIEW_LOG_URL }}
          GITHUB_TOKEN: ${{ secrets.CODE_TOKEN }}
          COMMIT_PROJECT: ${{ env.REPO_NAME }}
          COMMIT_BRANCH: ${{ env.BRANCH_NAME }}
          COMMIT_AUTHOR: ${{ env.COMMIT_AUTHOR }}
          COMMIT_MESSAGE: ${{ env.COMMIT_MESSAGE }}

          GIT_DIFF_FILE_PATH: ${{ env.GIT_DIFF_FILE_PATH }}
          # 微信配置 「https://mp.weixin.qq.com/debug/cgi-bin/sandboxinfo?action=showinfo&t=sandbox/index」
          #          WEIXIN_APPID: ${{ secrets.WEIXIN_APPID }}
          #          WEIXIN_SECRET: ${{ secrets.WEIXIN_SECRET }}
          #          WEIXIN_TOUSER: ${{ secrets.WEIXIN_TOUSER }}
          #          WEIXIN_TEMPLATE_ID: ${{ secrets.WEIXIN_TEMPLATE_ID }}
          # OpenAi - ChatGLM 配置「https://open.bigmodel.cn/api/paas/v4/chat/completions」、「https://open.bigmodel.cn/usercenter/apikeys」
          API_KEY: ${{ secrets.CHATGLM_API_KEY }}
          MODEL: ${{ secrets.MODEL }}
          EMAILS: ${{ secrets.EMAILS }}
